name: prepare-release

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: "New release tag to create"
        required: true
        type: string
  push:
    branches:
      - philippsauter/sc-101978/csi-automate-manifest-release
#dummy change

jobs:
  prepare-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - run: make go.mk
      - run: |
          git config --global user.email "tooling@exoscale.ch"
          git config --global user.name "Exoscale Tooling"
        # - run: "make prepare-release NEW_VERSION=${{ inputs.release-tag }}"
      - run: make prepare-release NEW_VERSION=vX.Y.Z
      - run: |
          git push origin philippsauter/sc-101978/csi-automate-manifest-release
